CREATE TABLE CLIENTE
    (CPFCLIENTE CHAR(12) NOT NULL,
    NOMECLIENTE CHAR(20) NOT NULL,
    SOBRENOMECLIENTE CHAR(20) NOT NULL,
    RUACLIENTE CHAR(30) NULL,
    NUMERORESIDCLIENTE INTEGER NULL,
    BAIRROCLIENTE CHAR(30) NULL,
    HISTORICOCLIENTE CHAR(100) NULL,
    PRIMARY KEY(CPFCLIENTE));

CREATE TABLE PRODUTOR
    (CPFPRODUTOR CHAR(12) NOT NULL,
    NOMEPRODUTOR CHAR(20) NOT NULL,
    SOBRENOMEPRODUTOR CHAR(20) NOT NULL,
    RUAPRODUTOR CHAR(30) NULL,
    NUMERORESIDPRODUTOR INTEGER NULL,
    BAIRROPRODUTOR CHAR(30) NULL,
    PRIMARY KEY(CPFPRODUTOR));
    
CREATE TABLE PRODUTO
    (IDPRODUTO CHAR(10) NOT NULL,
    NOMEPRODUTO CHAR(20) NOT NULL,
    DIAVALIDADEPRODUTO INTEGER NULL,
    MESVALIDADEPRODUTO INTEGER NULL,
    ANOVALIDADEPRODUTO INTEGER NULL,
    TIPOPRODUTO CHAR(15) NULL,
    PRECOPRODUTO FLOAT NOT NULL,
    CPFPRODUTOR CHAR(12) NOT NULL,
    PRIMARY KEY (IDPRODUTO),
    FOREIGN KEY (CPFPRODUTOR) REFERENCES PRODUTOR(CPFPRODUTOR),
    CHECK(PRECOPRODUTO > 0));

CREATE TABLE PEDIDO
    (NUMPEDIDO INTEGER NOT NULL,
    VALORPEDIDO FLOAT NOT NULL,
    DIAPEDIDO INTEGER NOT NULL,
    MESPEDIDO INTEGER NOT NULL,
    ANOPEDIDO INTEGER NOT NULL,
    RUAENTREGA CHAR(30) NOT NULL,
    NUMERORESIDENTREGA INTEGER NOT NULL,
    BAIRROENTREGA CHAR(30) NOT NULL,
    CPFPRODUTOR CHAR(12) NOT NULL,
    CPFCLIENTE CHAR(12) NOT NULL,
    PRIMARY KEY(NUMPEDIDO),
    FOREIGN KEY (CPFPRODUTOR) REFERENCES PRODUTOR(CPFPRODUTOR),
    FOREIGN KEY (CPFCLIENTE) REFERENCES CLIENTE(CPFCLIENTE),
    CHECK (VALORPEDIDO > 0));

CREATE TABLE COMPOSTO
    (IDPRODUTO CHAR(10) NOT NULL,
    NUMPEDIDO INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    PRIMARY KEY(IDPRODUTO, NUMPEDIDO),
    FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO),
    FOREIGN KEY (NUMPEDIDO) REFERENCES PEDIDO(NUMPEDIDO),
    CHECK(QUANTIDADE > 0));